### ISSUE TITLE
Add blade directives in boot method

### ISSUE THREAD

**Issue by Atiladanvi** [yoeunes/toastr#11]
I can't get render blade directives in many causes. In docs i can see: Blade directive need to be registered in boot method. I can resolve my trouble whit this.

**Comment by Atiladanvi** [comment]
```
 public function boot()
    {
        $source = realpath($raw = __DIR__.'/../config/toastr.php') ?: $raw;

        if ($this->app instanceof LaravelApplication && $this->app->runningInConsole()) {
            $this->publishes([$source => config_path('toastr.php')]);
        } elseif ($this->app instanceof LumenApplication) {
            $this->app->configure('toastr');
        }

        $this->mergeConfigFrom($source, 'toastr');

        $this->registerBladeDirectives();
    }
```
https://laravel.com/docs/5.7/blade#custom-if-statements

**Comment by yoeunes** [comment]
Hello @Atiladanvi, thanks for the report, a new version was released to fix that issue, can you update the package to v1.1.1, and give me your feed back again.
