### ISSUE TITLE
Config file not publishing

### ISSUE THREAD

**Issue by Ir8Coder** [yoeunes/toastr#13]
First, THANK YOU for the hard work of making this happen.  It makes it much easier than having to reinvent the wheel when it comes to my projects.  🥇 

When I used the method of publishing the config file that you specified in the readme, it does not publish to the config directory in Laravel.

> As optional if you want to modify the default configuration, you can publish the configuration file:
> $ php artisan vendor:publish --provider='Yoeunes\Toastr\ToastrServiceProvider' --tag="config"

I worked around the issue by modifying the config file that is in the src package, but I do not like doing that.

Thanks again!

**Comment by Ir8Coder** [comment]
Disregard!!  Sorry!  I confused this package with the notify package.  All is well!

**Comment by yoeunes** [comment]
Thank you @Ir8Coder for using both packages, i will fix the notify package as soon as possible, thanks for reporting ^^

**Comment by yoeunes** [comment]
You can now update to notify package to v1.0.2
