### ISSUE TITLE
Limit the number of displayed toasts or option to clear the toasts

### ISSUE THREAD

**Issue by rtfmfm** [yoeunes/toastr#15]
Hello! 
At first place, I want to thank you for this project! It's great.

I have an issue using it in my app, because I need the option to set the maximum number of displayed toasts to 1, or option to clear previous toasts before the last toastr('') in the controller.

Are there such options available?

Thank you in advance!

**Comment by yoeunes** [comment]
Hello @rtfmfm thank you for using the toastr package, right now their is no option to limit the number of toastr it's a great idea i will try to implement it for later, but for your problem you can clean all toastr with the `clear()`method

```php
toastr()->clear();
```

**Comment by yoeunes** [comment]
Hello again, i just push v1.2 which include 'maxItems' in the config file with limits the number of displayed toasts, and you can also set the limit in your controller 

```php
toastr()->maxItems(3);
```

**Comment by rtfmfm** [comment]
Thank you very much! That was really fast!
It's fine now.

THANK YOU!

**Comment by yoeunes** [comment]
you're welcome dude ^^
