### ISSUE TITLE
not working with Laravel 7.

### ISSUE THREAD

**Issue by iwaheedshahzad** [yoeunes/toastr#18]
- Toastr Version: #.#.#
- Laravel Version: 7
- PHP Version: 7.3.*

### Description:
Toastr Is unable to install in laravel 7

### Steps To Reproduce:
Kindly test it make installabale

**Comment by yoeunes** [comment]
Hello @iwaheedshahzad thank's for your feedback.

Can you please show the composer output? For me the installation was successful for **Laravel 7.1** and **php 7.3**.

![Screenshot from 2020-03-12 13-16-47](https://user-images.githubusercontent.com/10859693/76521208-a2429080-6464-11ea-84ed-038b926bf5b6.png)

![Screenshot from 2020-03-12 13-18-59](https://user-images.githubusercontent.com/10859693/76521218-a8387180-6464-11ea-9006-e797f5f2cc1e.png)
