### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by nessor** [yoeunes/toastr#19]
- Toastr Version: 1.2.2
- Laravel Version: 6.15.1
- PHP Version: 7.3.9

### Description:
As described in #13, publishing the config file currently fails with the error message "Unable to locate publishable resources".

### Steps To Reproduce:
Try to publish the config file

![image](https://user-images.githubusercontent.com/3463261/76595638-74a92600-64fc-11ea-9a2a-4e34ff404864.png)

**Comment by yoeunes** [comment]
Hello @nessor thank's for your feedback.

Can you please upgrade to v1.2.3 and try again?

**Comment by nessor** [comment]
Hey @yoeunes 

I just ran the update. Unfortunately the identical error still appears.

**Comment by MGeurts** [comment]
Same problem here.

Toastr Version: 1.2.3
Laravel Version: 7.14.1
PHP Version: 7.4.6

**Comment by abdulsalam-emesh** [comment]
i have the same problem
i ran the update but the problem is still there an cant publish the config file

**Comment by yoeunes** [comment]
hello @abdulsalam-emesh, can u please tell which operating system do you use ?

![Screenshot from 2020-10-27 13-41-57](https://user-images.githubusercontent.com/10859693/97303186-5e1cc880-185a-11eb-88b1-fa155b36c266.png)

can you please create a PR for windows, or share your screen with me
please contact me at : younes.khoubza@gmail.com

**Comment by yoeunes** [comment]
Hello @abdulsalam-emesh 

Can you please upgrade to v1.2.5 and try again?

![Screenshot from 2020-10-27 14-10-37](https://user-images.githubusercontent.com/10859693/97306104-49daca80-185e-11eb-85a4-11396e34b1f2.png)

**Comment by abdulsalam-emesh** [comment]
Hello @yoeunes 
I'm using windows as an operating system and I have upgradet to to v1.2.5 but unfortunately it still dose not work by publishing the config file
for now I'v copied it manually  
this is from composer.lock

![Unbenannt](https://user-images.githubusercontent.com/47454446/97424241-badaba80-1910-11eb-8119-a3dde7f22923.PNG)

and from console

![Unbenannt](https://user-images.githubusercontent.com/47454446/97424369-e65da500-1910-11eb-8683-427085a238c5.PNG)

**Comment by 3tew** [comment]
I have the same problem too

Toastr Version: 1.2.5
Laravel Version: 8.11.2
PHP Version: 7.4.11

**Comment by EmmanuelAyTuz** [comment]
> I have the same problem too
> 
> Toastr Version: 1.2.5
> Laravel Version: 8.11.2
> PHP Version: 7.4.11

Try to run this command **php artisan vendor:publish** and select  **_Provider: Yoeunes\Toastr\ToastrServiceProvider_**

**Comment by yoeunes** [comment]
hello guys, sorry for the late reponse, i finnaly was able to test on a windows compouter .

@EmmanuelAyTuz you are right, this is the way to go for windows : 

![Screenshot from 2020-12-29 11-28-38](https://user-images.githubusercontent.com/10859693/103277521-82676380-49c9-11eb-9b83-48e9620e7314.png)
