### ISSUE TITLE
Using toastr with ajax

### ISSUE THREAD

**Issue by samuelhgf** [yoeunes/toastr#20]
- Toastr Version: 1.2.3
- Laravel Version: 7.1.3
- PHP Version: 7.4.3

### Description:
Hi, there is any way to render the toastr without refresh or redirect the user? This would be nice for using with ajax requests.

**Comment by yoeunes** [comment]
hi @samuelhgf, thanks for using this package.
You could do something like this:

```php
// add a new route to get the notifications from the session:
Route::get('/toastr', 'ToastrController');
```

```php
<?php

namespace App\Http\Controllers;

class ToastrController
{
    public function __invoke()
    {
        $notifications = session('toastr::notifications', []);
        $max = config('toastr.maxItems') ?: 0;

        return response()->json([
            'options' => config('toastr.options', []),
            'notifications' => array_slice($notifications, -$max),
        ]);
    }
}
```

```js
// add this snippet of code in your view template
<script type="text/javascript">
$(document).ready(function () {
            $.get('/toastr', function (response) {
                toastr.options = response.options;
                response.notifications.forEach(function (notification) {
                    toastr[notification.type](notification.message, notification.title, notification.options);
                });
            }, 'json');
        });
</script>
```

can you please confirm if this is working for you ?

**Comment by yoeunes** [comment]
![Screenshot from 2020-03-19 08-37-38](https://user-images.githubusercontent.com/10859693/77043100-1af1a180-69bd-11ea-942f-9823a56b7fb1.png)
![Screenshot from 2020-03-19 08-38-25](https://user-images.githubusercontent.com/10859693/77043105-1cbb6500-69bd-11ea-9bb7-ffd086a29484.png)
![Screenshot from 2020-03-19 08-38-37](https://user-images.githubusercontent.com/10859693/77043107-1d53fb80-69bd-11ea-862d-f94e0ac7fda0.png)

**Comment by samuelhgf** [comment]
Hi @yoeunes 
Thanks for the support!

I fix it by calling the tostar JavaScript method in the ajax response.

![Captura de Tela 2020-03-19 às 06 07 50](https://user-images.githubusercontent.com/16768378/77050085-f808c280-69a7-11ea-87ac-f5be77af0dbb.png)

**Comment by yoeunes** [comment]
good that you fixed it
