### ISSUE TITLE
The default CSS class 'toast' gets overlapped by Bootstrap

### ISSUE THREAD

**Issue by nmenescardi** [yoeunes/toastr#21]
- Toastr Version: 1.2.3
- Laravel Version: 7
- PHP Version: 7.3

### Description:
The default CSS class 'toast', used by default, gets overridden for the same class used by Bootstrap. So, Bootstrap adds extra styles that breaks Toastr boxes. 

I was able to solve it adding a `config/toastr.php` file and using another class, like: `'toastClass'        => 'toastr'`

### Steps To Reproduce:
Just installing Bootstrap and Toastr, and firing any msg

**Comment by akunbeben** [comment]
nice catch man, I was trying to figure it out and makes me confused for a while

**Comment by yoeunes** [comment]
Thank you @nmenescardi for reporting the issue
