### ISSUE TITLE
jQuery Clashes

### ISSUE THREAD

**Issue by NAK-Technologies** [yoeunes/toastr#32]
**Describe the bug**
package's jquery cdn often clashes with preloaded project's jquery and causes other libraries to malfunction.
**To Reproduce**
1. Add a jquery cdn in your laravel project's base file.
2. Use any other library which manipulates the DOM
3. Execute toastr()
4. Check console for the error of other library not found or "something is not a function"

**Expected behavior**
It should run smoothly as it was without the toast
**Screenshots**
![image](https://user-images.githubusercontent.com/81828354/212205945-0eb3b09e-50f1-41b2-a056-73f937f709c3.png)
Error occur with the toastr
![image](https://user-images.githubusercontent.com/81828354/212206177-c4855bb3-2c67-41be-af35-dd3bd206586c.png)

![image](https://user-images.githubusercontent.com/81828354/212205759-f0fe60a1-abc5-491e-9f2c-6966ba4bf744.png)
After commenting this cdn it is working as it should.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yoeunes** [comment]
Hello @NAK-Technologies, thank you for providing a clear description of the issue. To clarify, `yoeunes/toastr` is just a proxy package that utilizes the functionality of [PHPFlasher](https://php-flasher.io/). To resolve the issue, please follow these steps:

1. First, check the configuration for [PHPFlasher](https://php-flasher.io/laravel/#-configuration) at https://php-flasher.io/laravel/#-configuration. Note that this configuration is specific to [PHPFlasher](https://php-flasher.io/) and not `yoeunes/toastr`.
2. Next, use the command `php artisan vendor:publish --force --tag=flasher-config` to publish the configuration of [PHPFlasher](https://php-flasher.io/):  `config/flasher.php` and `config/flasher_toastr.php`
3. Thereafter, navigate to the file `config/flasher_toastr.php`.
4. Lastly, remove the line referencing jQuery from the configuration file.

Please let me know if this resolves the issue or if you have any further questions 🙏.

**Comment by NAK-Technologies** [comment]
![image](https://user-images.githubusercontent.com/81828354/212390616-0c323aef-8b2f-4b21-876c-e2ed083ef346.png)
this is my config folder as you can see it is not publishing flasher_toastr.php

**Comment by yoeunes** [comment]
Can you upgrade to `v2.3.0` and follow the steps again

**Comment by yoeunes** [comment]
Closed as it's fixed in `v2.3.0`
