### ISSUE TITLE
Not popping up when used in methods

### ISSUE THREAD

**Issue by jamesautodude** [yoeunes/toastr#33]
When using in a method like Store or Update, the toast never pops up

When used in the index method it does pop up... So it's setup correctly, it's just not working after a redirect

**Comment by yoeunes** [comment]
Hello @jamesautodude, thank you for bringing this issue to my attention. To better understand the problem and find a solution, please provide the following details:

* If possible, please provide a simple demo on a Github project that reproduces the issue. This will help me to see the exact steps you are taking and the environment in which you are running the code.

If you are unable to provide a demo, please provide the following:

* Your Laravel version.
* Your PHP version.
* The steps to reproduce the issue, including the specific code you are using and any additional information that you think may be relevant.

Providing this information will help me investigate the issue and find a solution. Thank you for your help in making toastr even better.

**Comment by jamesautodude** [comment]
Sorry I was in a rush

Anyways, here's some info:

Laravel version 9
PHP version 8.1
I have a simple controller with typical resources like: index, show, edit, store, update, destroy

I tried as a test, putting the following in the `index()` method:
`toastr()->success('testing');`

The above pops up the notice and it disappears properly

But, when I run the `store()` method, as well as redirect, it doesn't show... Here's a simplified example, unfortunately not my exact code but just giving an idea of the issue:

`
public function store(Request $request)
{
  Post::create([
      'title' => $request->title,
      'body' => $request->body,
  ]);
  
  toastr()->success('Post Created');
  return redirect()->route('posts.index');
}
`

When doing it this way, nothing shows on the posts `index()` view

**Comment by jamesautodude** [comment]
Hello, I ran Laravel Shift to improve/fix my coding, and now it works - so must've been some bad practice I was doing

Thank you!
