### ISSUE TITLE
Hello there is problem in jsdeliver cdn in egypt https://cdn.jsdelivr.net/npm/@flasher/flasher@1.2.4/dist/flasher.min.js is blocked in egypt what is the replacement ? 

### ISSUE THREAD

**Issue by mohamedSaidOthman** [yoeunes/toastr#38]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, iOS]

**Smartphone (please complete the following information):**

**Severity**
- [ ] High
- [ ] Medium
- [ ] Low

**Related Issues**
- #<NUMBER>

**Additional context**
 - Provide version of the yoeunes/toastr.
 - Provide the error log or any other relevant debugging information.
 - Add any other context about the problem here.

**Comment by yoeunes** [comment]
Hi Mohamed,

Thanks for bringing this to my attention. As a workaround, please use the Unpkg CDN instead. You can do so by replacing the jsDelivr URL in your flasher config with the following Unpkg URL:

https://www.unpkg.com/@flasher/flasher@1.3.1/dist/flasher.min.js

Please let me know if this solves your issue. If you continue to encounter problems, don't hesitate to reach out.

Best Regards,
Younes

**Comment by mohamedSaidOthman** [comment]
your new cdn works fine but there is issue after action no toastr appears
gives me error 
flasher.min.js:1 Uncaught Error: Unable to resolve "toastr" notification factory, did you forget to register it?

**Comment by yoeunes** [comment]
Please consider using the same version, “1.2.4” instead of “1.3.1” for both `flasher` and `flasher-toastr` as the one who failed with `jsdeliver`:

https://www.unpkg.com/@flasher/flasher@1.2.4/dist/flasher.min.js
https://www.unpkg.com/@flasher/flasher-toastr@1.2.4/dist/flasher-toastr.min.js

**Comment by mohamedSaidOthman** [comment]
thank you very much, 1.2.4 version is worked successfully , 
thank you again. @yoeunes

**Comment by yoeunes** [comment]
Great to hear it's working now! Don't hesitate to reach out if you have any more issues or questions.
