### ISSUE TITLE
The response is not a view.

### ISSUE THREAD

**Issue by fonsvalidsign** [yoeunes/toastr#42]
**Describe the bug**
In our application, we often assert if the correct view is returned like so:

```php
$response = $this->get(route('index'));

$response->assertOk()
    ->assertViewIs('dashboard.index');
```

This works with Laravel 9 and your yoeunes/toastr v1, but since upgrading to Laravel 10 and yoeunes/toastr v2 all tests that use `assertViewIs` now return the following error: `The response is not a view.`

I think this may be caused by adding the CDN link to flasher in every view.

*Sidenote* The pages that "don't return a view" do still work as intended.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a blank Laravel project (`composer create-project laravel/laravel 'project-name'`)
2. Change `tests/Feature/Exampletext`: replace `->assertStatus(200)` with `->assertOk()->assertViewIs('welcome')`.
3. Run the test, see that this works.
4. Add yoeunes/toastr v2 to the project (`composer require yoeunes/toastr`)
5. Run the test again, see that it fails.

**Expected behavior**
What should otherwise be valid views in Laravel, should not suddenly become invalid, or no views.

**Screenshots**
![image](https://github.com/yoeunes/toastr/assets/145024492/4d9c7790-544d-406e-bc4c-21999db50d5c)

**Desktop (please complete the following information):**
 - OS: The application runs in a Debian Linux pod (`FROM php:8-apache`). This problem also occurs when running it in macOS 14.2.1 (23C71)
 - Testsuite: PHPUnit 10
 - Version: yoeunes/toastr is version 2.3

**Severity**
- [x] High (as we need this to work and we need to upgrade to Laravel 10 which does not work with yoeunes/toastr v2)
- [ ] Medium
- [ ] Low

**Comment by yoeunes** [comment]
Hi Fons (@fonsvalidsign) 👋,

Thanks for bringing the issue to my attention!

The fix is now live in `yoeunes/toastr` v2.3.1. 🚀 Could you please give it a try and let me know if it resolves the view assertion test issue?

If you have any more issues or questions, feel free to reach out.

Best regards,
Younes
